#!/usr/bin/env bash

echo "------------------------"
echo "Running File service"
echo "------------------------"
#iceflix-file --Ice.Config=configs/fileservice.config
python3 iceflix/file.py --Ice.Config=configs/fileservice.config
